# Generated by Django 3.2.12 on 2022-03-28 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_year', models.IntegerField()),
                ('car_make', models.CharField(max_length=200)),
                ('car_model', models.CharField(max_length=200)),
                ('car_comments', models.TextField()),
                ('price_type', models.CharField(max_length=200)),
                ('price_dap', models.IntegerField()),
                ('price_egc', models.IntegerField()),
                ('price_advertised', models.IntegerField()),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_phone', models.IntegerField()),
                ('contact_email', models.CharField(max_length=200)),
                ('dealer_abn', models.CharField(max_length=200)),
                ('car_isFlagged', models.BooleanField(default=False)),
            ],
        ),
    ]
