# Generated by Django 3.2.12 on 2022-03-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_username', models.CharField(max_length=200)),
                ('user_password', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=200)),
                ('user_number', models.CharField(max_length=200)),
                ('user_email', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='contact_phone',
        ),
        migrations.AddField(
            model_name='car',
            name='contact_number',
            field=models.CharField(default='daskete', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
