# Generated by Django 3.2.12 on 2022-03-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0002_auto_20220327_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('enquiry_id', models.AutoField(primary_key=True, serialize=False)),
                ('enquiry_number', models.CharField(max_length=200)),
                ('enquiry_email', models.CharField(max_length=200)),
                ('enquiry_content', models.CharField(max_length=200)),
                ('enquiry_type', models.CharField(max_length=200)),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
