# Generated by Django 3.2.12 on 2022-03-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0003_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_abn',
            field=models.CharField(default='12312312336', max_length=200),
            preserve_default=False,
        ),
    ]
